title: 'SPINE Research Group'
description: 'Security - Privacy - Intelligence - Edge Computing'
url: 'https://spine-research-group.github.io'
baseurl: ''
permalink: pretty

collections:
  services:
    output: false
  team:
    output: false
  people:
    output: false
  news:
    output: false
  publications:
    output: false
  alumni:
    output: false

sass:
  style: compressed
  implementation: sassc

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - design_reference.md
